---
abstract: 'Asynchronous redis client using hiredis and EV'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Devel::Refcount: '0'
  ExtUtils::CBuilder: '0'
  Module::Build::Pluggable::ReadmeMarkdownFromPod: '0.04'
  Module::Build::Pluggable::XSUtil: '1.02'
  Pod::Markdown: '0'
  Test::Deep: '0'
  Test::More: '0.98'
  Test::RedisServer: '0.12'
  Test::TCP: '1.18'
configure_requires:
  EV::MakeMaker: '0'
  ExtUtils::ParseXS: '2.21'
  Module::Build: '0.42'
  Module::Build::Pluggable::ReadmeMarkdownFromPod: '0.04'
  Module::Build::Pluggable::XSUtil: '1.02'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: EV-Hiredis
no_index:
  directory:
    - deps
requires:
  EV: '4.11'
  XSLoader: '0.02'
resources:
  license: http://dev.perl.org/licenses/
version: '0.02'
